### ISSUE TITLE
Test devbot3

### ISSUE THREAD

**Issue by tolatolatop** [ZekangZhouKGR/devfastapi#8]
添加一个接口，通过url接受username并返回hello username

**Comment by ZekangZhouKGR** [comment]
要添加一个接口，通过URL接受username并返回"Hello username"，可以在devfastapi.py文件中添加以下代码：

```python
@app.get("/hello/{username}")
async def hello(username: str):
    return {"message": f"Hello {username}"}
```

这样，当访问`/hello/{username}`时，将返回`{"message": "Hello username"}`，其中`username`是通过URL传递的参数。

**Comment by tolatolatop** [comment]
使用你的coding技能，提交代码到仓库PR

**Comment by tolatolatop** [comment]
使用你的coding技能 添加一个接口，通过url接受username并返回hello username
